name: integration_test_example_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/